/**
 * Gleam reference material given to the coach model instead of case-by-case prompt rules:
 * - reference/gleam/syntax.md: hand-written, compile-verified syntax reference (goes into the system prompt).
 * - reference/gleam/generated/stdlib.json: signatures of the grader's pinned gleam_stdlib, generated by
 *   tools/gleam-reference; only modules the code imports are sent.
 */
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

interface ModuleReference {
  readonly module: string;
  readonly summary: string;
  readonly lines: readonly string[];
}

interface StdlibReference {
  readonly package: string;
  readonly version: string;
  readonly modules: readonly ModuleReference[];
}

const dir = fileURLToPath(new URL("../reference/gleam/", import.meta.url));

function readOptional(path: string): string {
  return existsSync(path) ? readFileSync(path, "utf8") : "";
}

const syntaxText = readOptional(`${dir}syntax.md`).trim();
const stdlibRaw = readOptional(`${dir}generated/stdlib.json`);
const stdlib: StdlibReference | null = stdlibRaw ? (JSON.parse(stdlibRaw) as StdlibReference) : null;

/** Changes whenever the reference material changes; part of the prompt version / feedback cache key. */
export const REFERENCE_HASH = createHash("sha256").update(syntaxText).update(stdlibRaw).digest("hex").slice(0, 8);

export function syntaxReference(): string {
  return syntaxText;
}

const IMPORT_RE = /^\s*import\s+(gleam\/[a-z_]+(?:\/[a-z_]+)*)/gm;

/** Modules imported by any of the given Gleam sources, in first-seen order. */
export function importedModules(sources: readonly string[]): string[] {
  const seen = new Set<string>();
  for (const src of sources) for (const m of src.matchAll(IMPORT_RE)) if (m[1]) seen.add(m[1]);
  return [...seen];
}

/**
 * Signatures for the modules the sources import (always at least gleam/list, the most common one), so the
 * model can only suggest functions that exist in the pinned version.
 */
export function stdlibReference(sources: readonly string[]): string {
  if (!stdlib) return "(표준 라이브러리 참고 자료 없음)";
  const wanted = new Set(importedModules(sources));
  wanted.add("gleam/list");
  const parts = [`${stdlib.package} ${stdlib.version} (the version the grader uses). Labels shown as \`label:\` are call labels.`];
  for (const m of stdlib.modules) {
    if (!wanted.has(m.module)) continue;
    parts.push(`## ${m.module}${m.summary ? ` — ${m.summary}` : ""}\n${m.lines.join("\n")}`);
  }
  return parts.join("\n\n");
}
