/**
 * Gleam reference material given to the coach model instead of case-by-case prompt rules:
 * - reference/gleam/syntax.md: hand-written, compile-verified syntax reference (goes into the system prompt).
 * - reference/gleam/generated/stdlib.json: signatures of the grader's pinned gleam_stdlib, generated by
 *   tools/gleam-reference; only modules the code imports are sent.
 */
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

interface ModuleReference {
  readonly module: string;
  readonly summary: string;
  readonly lines: readonly string[];
}

interface StdlibReference {
  readonly package: string;
  readonly version: string;
  readonly modules: readonly ModuleReference[];
}

const dir = fileURLToPath(new URL("../reference/gleam/", import.meta.url));

function readOptional(path: string): string {
  return existsSync(path) ? readFileSync(path, "utf8") : "";
}

const syntaxText = readOptional(`${dir}syntax.md`).trim();
const stdlibRaw = readOptional(`${dir}generated/stdlib.json`);
const stdlib: StdlibReference | null = stdlibRaw ? (JSON.parse(stdlibRaw) as StdlibReference) : null;

/** Changes whenever the reference material changes; part of the prompt version / feedback cache key. */
export const REFERENCE_HASH = createHash("sha256").update(syntaxText).update(stdlibRaw).digest("hex").slice(0, 8);

export function syntaxReference(): string {
  return syntaxText;
}

const IMPORT_RE = /^\s*import\s+(gleam\/[a-z_]+(?:\/[a-z_]+)*)/gm;

/** Modules imported by any of the given Gleam sources, in first-seen order. */
export function importedModules(sources: readonly string[]): string[] {
  const seen = new Set<string>();
  for (const src of sources) for (const m of src.matchAll(IMPORT_RE)) if (m[1]) seen.add(m[1]);
  return [...seen];
}

/**
 * Signatures for the modules the sources import (always at least gleam/list, the most common one), so the
 * model can only suggest functions that exist in the pinned version.
 */
export function stdlibReference(sources: readonly string[]): string {
  if (!stdlib) return "(표준 라이브러리 참고 자료 없음)";
  const wanted = new Set(importedModules(sources));
  wanted.add("gleam/list");
  const parts = [`${stdlib.package} ${stdlib.version} (the version the grader uses). Labels shown as \`label:\` are call labels.`];
  for (const m of stdlib.modules) {
    if (!wanted.has(m.module)) continue;
    parts.push(`## ${m.module}${m.summary ? ` — ${m.summary}` : ""}\n${m.lines.join("\n")}`);
  }
  return parts.join("\n\n");
}

// ---------- On-demand lookups (chat agent tools) ----------

interface SyntaxSection {
  readonly title: string;
  readonly body: string;
}

const syntaxSections: readonly SyntaxSection[] = syntaxText
  .split(/^## /m)
  .slice(1)
  .map((chunk) => {
    const nl = chunk.indexOf("\n");
    return { title: chunk.slice(0, nl).trim(), body: `## ${chunk}`.trim() };
  });

export function syntaxTopics(): readonly string[] {
  return syntaxSections.map((s) => s.title);
}

/** Up to `max` sections whose title best matches the query words (case-insensitive). */
export function lookupSyntax(query: string, max = 2): string {
  const words = query.toLowerCase().split(/[^a-z0-9|`/{}_-]+/).filter((w) => w.length > 1);
  const scored = syntaxSections
    .map((s) => {
      const title = s.title.toLowerCase();
      const body = s.body.toLowerCase();
      const score = words.reduce((n, w) => n + (title.includes(w) ? 3 : 0) + (body.includes(w) ? 1 : 0), 0);
      return { s, score };
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, max);
  if (scored.length === 0) return `일치하는 문법 항목이 없습니다. 항목: ${syntaxTopics().join(", ")}`;
  return scored.map((x) => x.s.body).join("\n\n");
}

/** Signature lines of one stdlib module, optionally filtered by a name fragment. */
export function lookupStdlib(moduleName: string, query?: string, max = 40): string {
  if (!stdlib) return "표준 라이브러리 참고 자료가 없습니다.";
  const normalized = moduleName.startsWith("gleam/") ? moduleName : `gleam/${moduleName}`;
  const mod = stdlib.modules.find((m) => m.module === normalized);
  if (!mod) return `${normalized} 모듈이 없습니다. 모듈: ${stdlib.modules.map((m) => m.module).join(", ")}`;
  const q = query?.trim().toLowerCase();
  const lines = q ? mod.lines.filter((l) => l.toLowerCase().split("(")[0]?.includes(q) || l.toLowerCase().includes(`.${q}`)) : mod.lines;
  if (lines.length === 0) return `${normalized}에 "${query}"와 일치하는 함수가 없습니다.`;
  const shown = lines.slice(0, max);
  const more = lines.length > shown.length ? `\n… ${lines.length - shown.length}개 더 있음 (query로 좁히세요)` : "";
  return `${stdlib.package} ${stdlib.version} ${normalized}\n${shown.join("\n")}${more}`;
}
